### ISSUE TITLE
Every letter has ~ before it in the dropdown options

### ISSUE THREAD

**Issue by KebabRonin** [xwikisas/application-task#166] opened 2024-12-03 09:25 UTC
![image](https://github.com/user-attachments/assets/155e76de-ffd1-4fbc-85e7-96b955fcdb01)

Reproduced on 3.6.1 and 3.6.2, seems to be an ui issue only.

**Comment by lamblinc** [comment] 2024-12-03 10:18
Duplicate of https://github.com/xwikisas/application-task/issues/161

**Closed** 2024-12-03 10:20 UTC
